apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-worker-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-worker-b
  template:
    metadata:
      labels:
        app: temporal-worker-b
    spec:
      containers:
      - name: worker
        image: awildphil/temporal-example-worker:4492f8c41e6a1a1c926a7acc2fad34ad01ea9691
        ports:
        - containerPort: 8080
        env:
        - name: TEMPORAL_SERVER
          value: "temporal-training-frontend.default.svc.cluster.local:7233"
        - name: CANARY_DEPLOYMENT_ATTRIBUTE
          value: "deployment-b"