apiVersion: v1
kind: Service
metadata:
  name: temporal-training-frontend
  namespace: default
spec:
  type: ExternalName
  externalName: temporal-training-green-frontend.green.svc.cluster.local
  ports:
    - protocol: TCP
      port: 7233