name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: TEMPORAL_WORKER_DEPLOYMENT

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.23

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      run: |
        docker build -t ${{ vars.DOCKERHUB_USERNAME }}/temporal-example-worker:${{ github.sha }} -t ${{ vars.DOCKERHUB_USERNAME }}/temporal-example-worker:latest Worker/.

    - name: Push Docker image
      run: |
        docker push ${{ vars.DOCKERHUB_USERNAME }}/temporal-example-worker:${{ github.sha }}
        docker push ${{ vars.DOCKERHUB_USERNAME }}/temporal-example-worker:latest